baseURL = "http://blog.atttx123.cn/"

theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true

DefaultContentLanguage = "zh-cn"
[languages]
  [languages.en]
    title = "atttx123's blog"
    contentDir = "content/en" # English
  [languages.zh-cn]
    title = "atttx123的blog"
    contentDir = "content/zh" # Chinese

[Params]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"

[Author]
  name = "atttx123"
  email = "atttx123@gmail.com"
  github = "atttx123"
  twitter = "atttx123"
  medium = "atttx123"
  stackoverflow = "atttx123"
